# Generated by Django 5.1.7 on 2025-04-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('img_url', models.URLField()),
                ('overview', models.TextField()),
                ('ingredients', models.TextField(help_text='Comma-separated list of ingredients')),
                ('time_to_prepare', models.CharField(max_length=50)),
                ('full_process', models.TextField()),
            ],
        ),
    ]
