# Generated by Django 5.1.7 on 2025-04-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_veg',
            field=models.BooleanField(default=True),
        ),
    ]
